FROM nginx:latest

# Init linux user. it gonna be changed in runtime by secret.
RUN useradd --create-home --shell /bin/bash hi && echo 'hi':'hi' | chpasswd
RUN echo 'root':'root' | chpasswd

# Change Public Linux Repository
RUN sed -i "s/archive.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list && sed -i "s/security.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list
RUN apt-get update -y -qq

# Instal basic tools
RUN apt-get install -y -qq curl
RUN apt-get install -y -qq net-tools
RUN apt-get install -y -qq iproute2
RUN apt-get install -y -qq openssh-server
RUN apt install -y nginx certbot python3-certbot-nginx