version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - 8888:8080
    volumes:
      - "./web/conf/default.conf:/etc/nginx/conf.d/default.conf"
    deploy:
      mode: global

  db:
    image: mariadb:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3333:3306
    deploy:
      mode: global

  db-monitor:
    image: phpmyadmin:latest
    ports:
      - 2253:80
    links:
      - db
    environment:
      PMA_HOST: db

  cs:
    build:
      context: ./cs
    volumes:
      - ./cs/init:/cs-init.d
      - ./cs/init.py:/init.py
    entrypoint: 'python3 /init.py &&'