version: '3.3'

services:
  web:
    build:
      context: ./web
      dockerfile: "./dockerfile"
    ports:
      - 80:80
      - 443:443
      
    volumes:
      - "./web/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/location:/etc/nginx/sites-available/location"
      - "./web/ssl:/etc/ssl"
    links:
      - app
      - db
    privileged: true
    # deploy:
    #   mode: global
  
  app:
    build:
      context: ./app
      dockerfile: "./dockerfile"
    command: ["pm2-runtime", "/app/conf/ecosystem.config.js"]
    ports:
      - 8252:8252
    volumes:
      - "./app/conf/:/app/conf"
      - "../static:/app/static"
      - "../src/dashboard-server/out:/app/src/server"
      - "../src/dashboard-server/node_modules:/app/src/server/src/node_modules"
    links:
      - db
    
  db:
    image: mariadb:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3333:3306
    deploy:
      mode: global

  db-monitor:
    image: phpmyadmin:latest
    ports:
      - 2253:80
    links:
      - db
    environment:
      PMA_HOST: db

  cs:
    build:
      context: ./cs
    volumes:
      - ./cs/init:/cs-init.d
      - ./cs/init.py:/init.py
    entrypoint: 'python3 /init.py &&'